export const copy = {
  common: {
    appName: 'FACECARD',
    loadingProfiles: 'Cargando perfiles...',
    loadingPanel: 'Cargando panel...',
    loadingBookings: 'Cargando reservas...',
    loadingTalentProfile: 'Cargando perfil...',
  },
  nav: {
    explore: 'Explorar',
    cities: 'Ciudades',
    about: 'Quiénes somos',
    contact: 'Contacto',
    bookings: 'Reservas',
    access: 'Acceder',
    dashboard: 'Panel',
    logout: 'Salir',
    menu: 'Menu',
    close: 'Cerrar',
    closeMenu: 'Cerrar menu',
    openMenu: 'Abrir menu',
    search: 'Buscar',
  },
  hero: {
    menu: {
      privacy: 'Politica de privacidad',
      cookies: 'Politica de cookies',
    },
    eyebrow: 'Reserva talento visual curado',
    title: 'Explora perfiles creativos y convierte ideas en producciones reales.',
    cta: 'Explorar talento',
    fallbackAlt: 'Retrato editorial',
  },
  home: {
    featuredEyebrow: 'Talento destacado',
    featuredTitle: 'Una seleccion premium de talento visual',
    featuredDescription: 'Perfiles elegidos por criterio editorial, calidad visual y experiencia profesional.',
    valueCards: {
      editorialTitle: 'Curaduria editorial',
      editorialDescription: 'Imagen limpia, criterio visual y nivel de agencia.',
      bookingTitle: 'Reserva simple',
      bookingDescription: 'Desde explorar hasta reservar en un flujo claro.',
      launchTitle: 'Foco local',
      launchDescription: 'Madrid, Barcelona, Valencia y Sevilla activas.',
    },
  },
  discover: {
    categoryHeader: {
      eyebrow: 'Talento',
      title: 'Explorar por especialidad',
      description: 'Bloques curados por especialidad con fichas claras y accion rapida.',
    },
    cityHeader: {
      eyebrow: 'Ciudades',
      title: 'Explorar por ciudad',
      description: 'Encuentra talento activo por ciudad en formato compacto.',
    },
    resultCountSuffix: 'perfiles activos',
    gridHint: 'Vista compacta: 4 fichas por fila en desktop',
    emptyTitle: 'Sin resultados',
    emptyMessage: 'Ajusta filtros para encontrar talento.',
    loadingBlocks: 'Curando seleccion...',
    categoryMeta: {
      model: {
        title: 'Modelos destacados',
        label: 'Modelo editorial',
        description: 'Perfiles para campanas, lookbooks y editoriales.',
      },
      photographer: {
        title: 'Fotografos destacados',
        label: 'Fotografo de moda',
        description: 'Talento para retrato, estudio y narrativa visual.',
      },
      'makeup artist': {
        title: 'Maquilladores destacados',
        label: 'Maquillador profesional',
        description: 'Especialistas en belleza editorial y piel limpia.',
      },
      'tattoo artist': {
        title: 'Tatuadores destacados',
        label: 'Tatuador creativo',
        description: 'Perfil artistico con precision y estilo.',
      },
      'creative director': {
        title: 'Directores creativos destacados',
        label: 'Direccion creativa',
        description: 'Concepto, narrativa y coherencia visual.',
      },
      stylist: {
        title: 'Estilistas destacados',
        label: 'Stylist editorial',
        description: 'Vestuario, silueta y cohesion de imagen.',
      },
      fallbackDescription: 'Bloque editorial de talento con ficha tecnica.',
    },
    citySection: {
      titleSuffix: 'destacados',
      descriptionPrefix: 'Talento activo para producciones en',
    },
  },
  filters: {
    searchPlaceholder: 'Buscar por nombre, especialidad o ciudad',
    dayRatePlaceholder: 'Tarifa maxima por dia',
    categories: {
      all: 'Todas las categorias',
      model: 'Modelo',
      photographer: 'Fotografo/a',
      makeupArtist: 'Maquillador/a',
      tattooArtist: 'Tatuador/a',
      creativeDirector: 'Director/a creativo/a',
      stylist: 'Estilista',
    },
    cities: {
      all: 'Todas las ciudades',
      madrid: 'Madrid',
      barcelona: 'Barcelona',
      valencia: 'Valencia',
      sevilla: 'Sevilla',
    },
    availability: {
      all: 'Cualquier disponibilidad',
      available: 'Disponible',
      campaign: 'Campana',
      studio: 'Estudio',
      editorial: 'Editorial',
    },
  },
  cards: {
    city: 'Ciudad',
    specialty: 'Especialidad',
    rate: 'Tarifa',
    daySuffix: '/dia',
    viewProfile: 'Ver perfil',
    viewSheet: 'Ver ficha',
    reserve: 'Reservar',
    activeShowcaseSuffix: 'activos en vitrina',
    sectionCityLabel: 'Ciudad',
    sectionSpecialtyLabel: 'Especialidad',
    noTalentsTitle: 'Sin talento disponible',
    noTalentsMessage: 'Cambia los filtros para seguir explorando.',
    categories: {
      model: 'Modelo',
      photographer: 'Fotografo/a',
      'makeup artist': 'Maquillador/a',
      'tattoo artist': 'Tatuador/a',
      'creative director': 'Director/a creativo/a',
      stylist: 'Estilista',
    },
  },
  bookingForm: {
    eyebrow: 'Reserva privada',
    title: 'Solicitud de reserva privada',
    projectType: 'Proyecto / Produccion',
    location: 'Ciudad o locacion del proyecto',
    budget: 'Presupuesto (EUR)',
    notes: 'Brief y requisitos',
    submit: 'Enviar solicitud',
    submitting: 'Enviando solicitud...',
  },
  talentProfile: {
    profileEyebrow: 'Perfil',
    bioTitle: 'Vision del perfil',
    rateDay: 'Tarifa por dia',
    rateSession: 'Tarifa por sesion',
    availability: 'Disponibilidad',
    portfolioEyebrow: 'Portfolio',
    portfolioTitle: 'Seleccion visual',
    portfolioDescription: 'Trabajo editorial y resultados de campana.',
    feedbackSuccess: 'Solicitud enviada con exito.',
    feedbackError: 'No pudimos enviar tu solicitud de reserva.',
    notFoundTitle: 'Perfil no disponible',
    notFoundMessage: 'Este perfil no esta disponible ahora.',
    accessToReservePrefix: 'Necesitas',
    accessToReserveLink: 'acceder',
    accessToReserveSuffix: 'para solicitar una reserva.',
  },
  login: {
    eyebrow: 'Acceso privado',
    title: 'Accede a Vigencia Talentos',
    subtitle: 'Accede con email o Face ID biometrico.',
    emailLabel: 'Email profesional',
    passwordLabel: 'Contrasena',
    emailPlaceholder: 'tu@correo.com',
    passwordPlaceholder: '********',
    activeMethod: 'Acceso manual: Email',
    faceMethod: 'Face ID: Acceso biometrico',
    submit: 'Entrar con email',
    submitting: 'Entrando...',
    error: 'No pudimos validar tu acceso. Revisa tus credenciales.',
    hintActivate: 'Activa Face ID una vez y luego entra sin contrasena.',
    hintDemo: 'Demo: talent1@facecard.local / password',
  },
  faceId: {
    eyebrow: 'Biometria activa',
    title: 'Acceso biometrico en tiempo real',
    subtitle:
      'Sistema de autenticacion biometrica para agencias de talento. Elimina contrasenas y protege accesos privados.',
    scanEngine: 'Motor biometrico',
    engineInactive: 'No activo',
    engineActive: 'Face API + TensorFlow',
    profileReady: 'Perfil biometrico listo',
    profilePending: 'Perfil biometrico pendiente',
    activated: 'Face ID habilitado',
    notActivated: 'Face ID sin habilitar',
    demoModeBadge: 'Modo demo de Vigencia Talentos',
    emailLabel: 'Email de acceso',
    emailPlaceholder: 'talent1@facecard.local',
    faceDetected: 'Rostro validado',
    noFace: 'Sin validacion de rostro',
    cameraOn: 'Camara activa',
    cameraOff: 'Camara apagada',
    blink: 'Parpadeo',
    turn: 'Giro',
    movement: 'Movimiento',
    antiSpoof: 'Anti-suplantacion',
    distance: 'Distancia',
    noDistance: 'N/A',
    referenceLoaded: 'Referencia biometrica cargada para validar acceso.',
    startScan: 'Iniciar escaneo',
    stopCamera: 'Detener camara',
    preparing: 'Preparando...',
    activate: 'Habilitar Face ID',
    activating: 'Habilitando...',
    access: 'Entrar con Face ID',
    validating: 'Validando...',
    statusReady: 'Listo para escaneo',
    statusCameraStopped: 'Camara detenida',
    statusNeedActivation: 'Habilita Face ID una vez con tu contrasena para continuar.',
    statusProfileLoaded: 'Perfil biometrico cargado. Inicia el escaneo.',
    statusDemoMode: 'Modo demo local activo. El acceso se realiza al validar el rostro.',
    statusAutoLogin: 'Rostro validado. Entrando automaticamente...',
    statusSingleFace: 'Debe haber un solo rostro frente a camara.',
    statusSearchingFace: 'Buscando rostro...',
    statusCenterFace: 'Centra el rostro dentro del aro',
    statusCompleteLiveness: 'Completa prueba de vida: parpadea, gira y mueve el rostro.',
    statusReadyToActivate: 'Rostro validado. Habilita Face ID.',
    statusReadyToAccess: 'Rostro validado. Acceso seguro listo.',
    statusAccessSuccess: 'Validacion completada. Entrando...',
    statusActivated: 'Face ID habilitado. Ya puedes entrar solo con escaneo.',
    errorEmailRequired: 'Escribe tu email para preparar Face ID.',
    errorPrepareProfile: 'No pudimos preparar tu perfil biometrico.',
    errorNoCameraAccess: 'Debes permitir camara para activar el acceso biometrico.',
    errorNoCameraSupport: 'Este navegador no permite usar camara para Face ID.',
    errorOpenCamera: 'No pudimos abrir la camara. Revisa permisos y vuelve a intentar.',
    errorProcessScan: 'No pudimos procesar el escaneo. Intenta nuevamente.',
    errorEmailForValidation: 'Escribe tu email para validar el acceso biometrico.',
    errorDescriptorMissing: 'No hay escaneo valido. Repite el proceso.',
    errorLivenessRequired: 'Completa la prueba de vida para un acceso seguro.',
    errorConfidenceLow: 'La confianza del escaneo es baja. Ajusta luz y encuadre.',
    errorAntiSpoofLow: 'La validacion anti-suplantacion no fue suficiente.',
    errorPasswordRequired: 'Escribe tu contrasena para activar Face ID.',
    errorActivateFirst: 'Primero habilita Face ID con email y contrasena.',
    errorActivateFace: 'No pudimos habilitar Face ID.',
    errorFaceAccess: 'No pudimos acceder con Face ID.',
  },
  dashboard: {
    eyebrow: 'Panel',
    welcome: (name) => `Hola, ${name ?? ''}`.trim(),
    description: 'Revisa reservas, estado de perfil y actividad en una vista limpia.',
    statuses: {
      pending: 'Pendientes',
      accepted: 'Aceptadas',
      rejected: 'Rechazadas',
      completed: 'Completadas',
    },
    profileTitle: 'Perfil de talento',
    noProfileTitle: 'Aun no tienes perfil',
    noProfileMessage: 'Crea tu perfil desde la API /me/talent-profile.',
    availability: 'Disponibilidad',
    availabilityMissing: 'Sin disponibilidad cargada.',
    totalBookings: 'Reservas totales',
    clientPanelTitle: 'Panel de cliente',
    clientPanelMessage: 'Tu historial esta en Reservas. El Perfil aplica para cuentas talento.',
  },
  bookings: {
    eyebrow: 'Reservas privadas',
    title: 'Panel de reservas',
    description: 'Gestiona solicitudes privadas en un flujo claro y seguro.',
    emptyTitle: 'Aun no hay solicitudes',
    emptyMessage: 'Cuando lleguen nuevas solicitudes, apareceran aqui.',
    status: {
      pending: 'Pendiente',
      accepted: 'Aceptada',
      rejected: 'Rechazada',
      completed: 'Completada',
    },
    dateLabel: 'Fecha',
    budgetLabel: 'Presupuesto',
    clientLabel: 'Cliente',
    privateClient: 'Cliente privado',
    talentFallback: 'Talento',
  },
  contact: {
    eyebrow: 'Contacto',
    title: 'Hablemos',
    description: 'Comparte tu consulta y te respondemos por email.',
    directChannels: 'Canales directos',
    generalEmail: 'Email general',
    generalEmailValue: 'hello@facecard.local',
    collaborationsEmail: 'Colaboraciones',
    collaborationsEmailValue: 'editorial@facecard.local',
    pressEmail: 'Prensa',
    pressEmailValue: 'press@facecard.local',
    scheduleTitle: 'Horario',
    scheduleValue: 'Lunes a viernes, 09:00 - 18:00 (CET)',
    form: {
      name: 'Nombre',
      email: 'Email',
      subject: 'Asunto',
      message: 'Mensaje',
      submit: 'Enviar',
      success: 'Mensaje enviado. Te respondemos pronto.',
    },
  },
  aboutFaq: {
    heroEyebrow: 'Quiénes somos',
    heroTitle: 'FACE CARD — TALENTO, IDENTIDAD Y ACCESO SEGURO',
    paragraphs: [
      'FaceCard nace como una evolución digital dentro del mundo de las agencias de talento.',
      'En entornos donde el acceso a castings, contenidos privados o plataformas internas debe estar controlado, la identidad no puede depender únicamente de contraseñas. Por eso desarrollamos un sistema que combina lo mejor de ambos mundos: autenticación tradicional y verificación biométrica.',
      'Trabajamos con perfiles donde la seguridad, la agilidad y la experiencia son clave. Modelos, creativos y profesionales acceden a sus espacios de forma rápida, sin fricción y con un nivel adicional de control sobre su identidad.',
      'La tecnología no es el objetivo, es la herramienta. Nuestro enfoque es claro: facilitar el acceso al talento adecuado, en el momento adecuado, de forma segura y eficiente.',
    ],
    visionTitle: 'NUESTRA VISIÓN',
    visionPoints: [
      'Simplificar el acceso a plataformas de talento',
      'Reducir fricción en procesos digitales',
      'Aumentar seguridad sin complicar la experiencia',
      'Integrar tecnología en flujos reales de trabajo',
    ],
    faqTitle: 'FAQ',
    faqs: [
      {
        question: '¿Qué es realmente FaceCard?',
        answer:
          'FaceCard es una solución de autenticación diseñada para entornos de talento que permite acceder mediante email o reconocimiento facial, mejorando tanto la experiencia como el control de identidad.',
      },
      {
        question: '¿Por qué aplicar tecnología biométrica en una agencia de talento?',
        answer:
          'Porque permite asegurar que la persona que accede es realmente quien dice ser, reduciendo suplantaciones y simplificando el acceso a plataformas internas, castings o contenido exclusivo.',
      },
      {
        question: '¿Cómo funciona el acceso con reconocimiento facial?',
        answer:
          'El sistema detecta el rostro del usuario en tiempo real, analiza sus características faciales y las compara con una referencia previamente registrada para validar su identidad.',
      },
      {
        question: '¿Es obligatorio usar reconocimiento facial?',
        answer:
          'No. El sistema está diseñado como un modelo híbrido, por lo que el usuario puede seguir accediendo mediante email y contraseña si lo prefiere.',
      },
      {
        question: '¿Qué problema principal resuelve este sistema?',
        answer:
          'Reduce la dependencia de contraseñas, mejora la experiencia de acceso y añade una capa adicional de seguridad en entornos donde la identidad es relevante.',
      },
      {
        question: '¿Qué amenaza querías evitar?',
        answer:
          'Principalmente spoofing básico, como intentos de suplantación con fotografías o imágenes en pantalla.',
      },
      {
        question: '¿El liveness detection elimina todo riesgo?',
        answer:
          'No. Reduce ataques simples, pero no sustituye una infraestructura biométrica de nivel empresarial. Es una capa de seguridad adicional útil para un entorno web y una demo funcional.',
      },
      {
        question: '¿Qué señales de liveness usaste?',
        answer:
          'Movimientos faciales observables en tiempo real, como parpadeo, giro y desplazamiento del rostro, para verificar presencia activa del usuario frente a cámara.',
      },
    ],
  },
  legal: {
    eyebrow: 'Legal',
    privacyTitle: 'Politica de privacidad',
    privacyDescription: 'Como usamos y protegemos tus datos en FACECARD.',
    cookieTitle: 'Politica de cookies',
    cookieDescription: 'Tipos de cookies y control de consentimiento.',
    cookieSections: [
      {
        title: '1. Cookies esenciales',
        body: 'Garantizan seguridad, sesion y funciones clave de la plataforma.',
      },
      {
        title: '2. Cookies analiticas',
        body: 'Nos ayudan a mejorar rendimiento, contenido y experiencia de navegacion.',
      },
      {
        title: '3. Cookies de marketing',
        body: 'Personalizan mensajes comerciales solo cuando das tu consentimiento.',
      },
      {
        title: '4. Preferencias',
        body: 'Puedes aceptar, rechazar o ajustar cookies opcionales en cualquier momento.',
      },
    ],
    privacySections: [
      {
        title: '1. Responsable',
        body: 'FACECARD gestiona esta plataforma para explorar y reservar talento creativo.',
      },
      {
        title: '2. Datos que usamos',
        body: 'Nombre, email, ciudad, datos de perfil, reservas y metadatos tecnicos.',
      },
      {
        title: '3. Finalidad',
        body: 'Usamos tus datos para acceder, gestionar reservas y mejorar el servicio.',
      },
      {
        title: '4. Conservacion y derechos',
        body: 'Conservamos datos el tiempo necesario. Puedes solicitar acceso, cambio o eliminacion.',
      },
      {
        title: '5. Seguridad',
        body: 'Aplicamos medidas tecnicas y organizativas para proteger tu informacion.',
      },
    ],
  },
  cookies: {
    bannerText:
      'Usamos cookies esenciales para que FACECARD funcione. Puedes aceptar, rechazar o ajustar preferencias.',
    preferences: 'Preferencias',
    reject: 'Rechazar',
    accept: 'Aceptar',
    closeNotice: 'Cerrar aviso de cookies',
    close: 'Cerrar',
    modalTitle: 'Configura cookies',
    essentialTitle: 'Cookies esenciales',
    essentialDescription: 'Necesarias para seguridad, sesion y funciones base.',
    analyticsTitle: 'Cookies analiticas',
    analyticsDescription: 'Nos ayudan a mejorar rendimiento y navegacion.',
    marketingTitle: 'Cookies de marketing',
    marketingDescription: 'Personalizan mensajes comerciales y promocionales.',
    rejectOptional: 'Rechazar opcionales',
    save: 'Guardar preferencias',
  },
  footer: {
    links: {
      contact: 'Contacto',
      privacy: 'Politica de privacidad',
      consent: 'Preferencias de consentimiento',
    },
    social: {
      instagram: 'Instagram',
      tiktok: 'TikTok',
      instagramUrl: 'https://www.instagram.com/',
      tiktokUrl: 'https://www.tiktok.com/',
    },
    rights: (year) => `Todos los derechos reservados - Copyright © ${year}`,
  },
  notFound: {
    code: '404',
    title: 'Pagina no encontrada',
    description: 'La pagina que buscas no esta disponible.',
    cta: 'Volver al inicio',
  },
}

