export const copy = {
  common: {
    appName: 'FACECARD',
    loadingProfiles: 'Cargando perfiles...',
    loadingPanel: 'Cargando panel...',
    loadingBookings: 'Cargando reservas...',
    loadingTalentProfile: 'Cargando perfil...',
  },
  nav: {
    explore: 'Explorar',
    cities: 'Ciudades',
    contact: 'Contacto',
    bookings: 'Reservas',
    access: 'Acceder',
    dashboard: 'Panel',
    logout: 'Salir',
    menu: 'Menu',
    close: 'Cerrar',
    closeMenu: 'Cerrar menu',
    openMenu: 'Abrir menu',
    search: 'Buscar',
  },
  hero: {
    menu: {
      privacy: 'Politica de privacidad',
      cookies: 'Politica de cookies',
    },
    eyebrow: 'Reserva talento visual curado',
    title: 'Explora perfiles creativos y convierte ideas en producciones reales.',
    cta: 'Explorar talento',
    fallbackAlt: 'Retrato editorial',
  },
  home: {
    featuredEyebrow: 'Talento destacado',
    featuredTitle: 'Una seleccion premium de talento visual',
    featuredDescription: 'Perfiles elegidos por criterio editorial, calidad visual y experiencia profesional.',
    valueCards: {
      editorialTitle: 'Curaduria editorial',
      editorialDescription: 'Imagen limpia, criterio visual y nivel de agencia.',
      bookingTitle: 'Reserva simple',
      bookingDescription: 'Desde explorar hasta reservar en un flujo claro.',
      launchTitle: 'Foco local',
      launchDescription: 'Madrid, Barcelona, Valencia y Sevilla activas.',
    },
  },
  discover: {
    categoryHeader: {
      eyebrow: 'Talento',
      title: 'Explorar por especialidad',
      description: 'Bloques curados por especialidad con fichas claras y accion rapida.',
    },
    cityHeader: {
      eyebrow: 'Ciudades',
      title: 'Explorar por ciudad',
      description: 'Encuentra talento activo por ciudad en formato compacto.',
    },
    resultCountSuffix: 'perfiles activos',
    gridHint: 'Vista compacta: 4 fichas por fila en desktop',
    emptyTitle: 'Sin resultados',
    emptyMessage: 'Ajusta filtros para encontrar talento.',
    loadingBlocks: 'Curando seleccion...',
    categoryMeta: {
      model: {
        title: 'Modelos destacados',
        label: 'Modelo editorial',
        description: 'Perfiles para campanas, lookbooks y editoriales.',
      },
      photographer: {
        title: 'Fotografos destacados',
        label: 'Fotografo de moda',
        description: 'Talento para retrato, estudio y narrativa visual.',
      },
      'makeup artist': {
        title: 'Maquilladores destacados',
        label: 'Maquillador profesional',
        description: 'Especialistas en belleza editorial y piel limpia.',
      },
      'tattoo artist': {
        title: 'Tatuadores destacados',
        label: 'Tatuador creativo',
        description: 'Perfil artistico con precision y estilo.',
      },
      'creative director': {
        title: 'Directores creativos destacados',
        label: 'Direccion creativa',
        description: 'Concepto, narrativa y coherencia visual.',
      },
      stylist: {
        title: 'Estilistas destacados',
        label: 'Stylist editorial',
        description: 'Vestuario, silueta y cohesion de imagen.',
      },
      fallbackDescription: 'Bloque editorial de talento con ficha tecnica.',
    },
    citySection: {
      titleSuffix: 'destacados',
      descriptionPrefix: 'Talento activo para producciones en',
    },
  },
  filters: {
    searchPlaceholder: 'Buscar por nombre, especialidad o ciudad',
    dayRatePlaceholder: 'Tarifa maxima por dia',
    categories: {
      all: 'Todas las categorias',
      model: 'Modelo',
      photographer: 'Fotografo/a',
      makeupArtist: 'Maquillador/a',
      tattooArtist: 'Tatuador/a',
      creativeDirector: 'Director/a creativo/a',
      stylist: 'Estilista',
    },
    cities: {
      all: 'Todas las ciudades',
      madrid: 'Madrid',
      barcelona: 'Barcelona',
      valencia: 'Valencia',
      sevilla: 'Sevilla',
    },
    availability: {
      all: 'Cualquier disponibilidad',
      available: 'Disponible',
      campaign: 'Campana',
      studio: 'Estudio',
      editorial: 'Editorial',
    },
  },
  cards: {
    city: 'Ciudad',
    specialty: 'Especialidad',
    rate: 'Tarifa',
    daySuffix: '/dia',
    viewProfile: 'Ver perfil',
    viewSheet: 'Ver ficha',
    reserve: 'Reservar',
    activeShowcaseSuffix: 'activos en vitrina',
    sectionCityLabel: 'Ciudad',
    sectionSpecialtyLabel: 'Especialidad',
    noTalentsTitle: 'Sin talento disponible',
    noTalentsMessage: 'Cambia los filtros para seguir explorando.',
    categories: {
      model: 'Modelo',
      photographer: 'Fotografo/a',
      'makeup artist': 'Maquillador/a',
      'tattoo artist': 'Tatuador/a',
      'creative director': 'Director/a creativo/a',
      stylist: 'Estilista',
    },
  },
  bookingForm: {
    eyebrow: 'Reservar talento',
    title: 'Solicitud de reserva',
    projectType: 'Tipo de proyecto',
    location: 'Ciudad o locacion',
    budget: 'Presupuesto (EUR)',
    notes: 'Detalles del proyecto',
    submit: 'Enviar reserva',
    submitting: 'Enviando...',
  },
  talentProfile: {
    profileEyebrow: 'Perfil',
    bioTitle: 'Vision del perfil',
    rateDay: 'Tarifa por dia',
    rateSession: 'Tarifa por sesion',
    availability: 'Disponibilidad',
    portfolioEyebrow: 'Portfolio',
    portfolioTitle: 'Seleccion visual',
    portfolioDescription: 'Trabajo editorial y resultados de campana.',
    feedbackSuccess: 'Reserva enviada.',
    feedbackError: 'No pudimos enviar la reserva.',
    notFoundTitle: 'Perfil no disponible',
    notFoundMessage: 'Este perfil no esta disponible ahora.',
    accessToReservePrefix: 'Necesitas',
    accessToReserveLink: 'acceder',
    accessToReserveSuffix: 'para reservar.',
  },
  login: {
    eyebrow: 'Acceso seguro',
    title: 'Accede a FACECARD',
    subtitle: 'Accede con email o Face ID.',
    emailLabel: 'Email profesional',
    passwordLabel: 'Contrasena',
    emailPlaceholder: 'tu@correo.com',
    passwordPlaceholder: '********',
    activeMethod: 'Metodo activo: Email',
    faceMethod: 'Face ID: Escaneo',
    submit: 'Acceder con email',
    submitting: 'Accediendo...',
    error: 'No pudimos acceder. Revisa tus credenciales.',
    hintActivate: 'Activa Face ID una vez con email y contrasena.',
    hintDemo: 'Demo: talent1@facecard.local / password',
  },
  faceId: {
    eyebrow: 'Face ID activo',
    title: 'Escaneo facial en tiempo real',
    subtitle:
      'Escaneo facial con prueba de vida. Activa Face ID una vez con tu contrasena y luego accede solo con rostro.',
    scanEngine: 'Motor de escaneo',
    engineInactive: 'No activo',
    engineActive: 'Face API + TensorFlow',
    profileReady: 'Perfil Face ID listo',
    profilePending: 'Perfil Face ID pendiente',
    activated: 'Face ID activado',
    notActivated: 'Face ID no activado',
    emailLabel: 'Email para Face ID',
    emailPlaceholder: 'talent1@facecard.local',
    faceDetected: 'Rostro detectado',
    noFace: 'Sin rostro',
    cameraOn: 'Camara activa',
    cameraOff: 'Camara apagada',
    blink: 'Parpadeo',
    turn: 'Giro',
    movement: 'Movimiento',
    antiSpoof: 'Anti spoof',
    distance: 'Distancia',
    noDistance: 'N/A',
    referenceLoaded: 'Referencia visual cargada para validar coincidencia.',
    startScan: 'Iniciar escaneo',
    stopCamera: 'Detener camara',
    preparing: 'Preparando...',
    activate: 'Activar Face ID',
    activating: 'Activando...',
    access: 'Acceder con Face ID',
    validating: 'Validando...',
    statusReady: 'Listo para escaneo',
    statusCameraStopped: 'Camara detenida',
    statusNeedActivation: 'Face ID requiere activacion inicial con email y contrasena.',
    statusProfileLoaded: 'Perfil biometrico cargado. Inicia escaneo.',
    statusSingleFace: 'Debe haber un solo rostro en camara.',
    statusSearchingFace: 'Buscando rostro...',
    statusCenterFace: 'Centra el rostro dentro del aro',
    statusCompleteLiveness: 'Completa prueba de vida: parpadea, gira y mueve el rostro.',
    statusReadyToActivate: 'Rostro validado. Activa Face ID.',
    statusReadyToAccess: 'Rostro validado. Puedes acceder.',
    statusAccessSuccess: 'Validacion completada. Accediendo...',
    statusActivated: 'Face ID activado. Ya puedes acceder solo con escaneo.',
    errorEmailRequired: 'Escribe tu email para preparar Face ID.',
    errorPrepareProfile: 'No pudimos preparar tu perfil de Face ID.',
    errorNoCameraAccess: 'Debes permitir acceso a la camara para usar Face ID.',
    errorNoCameraSupport: 'Este navegador no permite usar camara para Face ID.',
    errorOpenCamera: 'No pudimos abrir la camara. Revisa permisos e intenta de nuevo.',
    errorProcessScan: 'No pudimos procesar el escaneo. Intenta nuevamente.',
    errorEmailForValidation: 'Escribe tu email para validar Face ID.',
    errorDescriptorMissing: 'No hay escaneo valido. Repite el proceso.',
    errorLivenessRequired: 'Completa la prueba de vida para continuar.',
    errorConfidenceLow: 'La confianza del escaneo es baja. Ajusta luz y encuadre.',
    errorAntiSpoofLow: 'La validacion anti-suplantacion no fue suficiente.',
    errorPasswordRequired: 'Escribe tu contrasena para activar Face ID.',
    errorActivateFirst: 'Primero activa Face ID con email y contrasena.',
    errorActivateFace: 'No pudimos activar Face ID.',
    errorFaceAccess: 'No pudimos acceder con Face ID.',
  },
  dashboard: {
    eyebrow: 'Panel',
    welcome: (name) => `Hola, ${name ?? ''}`.trim(),
    description: 'Revisa reservas, estado de perfil y actividad en una vista limpia.',
    statuses: {
      pending: 'Pendientes',
      accepted: 'Aceptadas',
      rejected: 'Rechazadas',
      completed: 'Completadas',
    },
    profileTitle: 'Perfil de talento',
    noProfileTitle: 'Aun no tienes perfil',
    noProfileMessage: 'Crea tu perfil desde la API /me/talent-profile.',
    availability: 'Disponibilidad',
    availabilityMissing: 'Sin disponibilidad cargada.',
    totalBookings: 'Reservas totales',
    clientPanelTitle: 'Panel de cliente',
    clientPanelMessage: 'Tu historial esta en Reservas. El Perfil aplica para cuentas talento.',
  },
  bookings: {
    eyebrow: 'Reservas',
    title: 'Gestion de reservas',
    description: 'Sigue cada reserva en una vista simple y ordenada.',
    emptyTitle: 'Aun no hay reservas',
    emptyMessage: 'Cuando lleguen nuevas reservas, apareceran aqui.',
    status: {
      pending: 'Pendiente',
      accepted: 'Aceptada',
      rejected: 'Rechazada',
      completed: 'Completada',
    },
    dateLabel: 'Fecha',
    budgetLabel: 'Presupuesto',
    clientLabel: 'Cliente',
    privateClient: 'Cliente privado',
    talentFallback: 'Talento',
  },
  contact: {
    eyebrow: 'Contacto',
    title: 'Hablemos',
    description: 'Comparte tu consulta y te respondemos por email.',
    directChannels: 'Canales directos',
    generalEmail: 'Email general',
    generalEmailValue: 'hello@facecard.local',
    collaborationsEmail: 'Colaboraciones',
    collaborationsEmailValue: 'editorial@facecard.local',
    pressEmail: 'Prensa',
    pressEmailValue: 'press@facecard.local',
    scheduleTitle: 'Horario',
    scheduleValue: 'Lunes a viernes, 09:00 - 18:00 (CET)',
    form: {
      name: 'Nombre',
      email: 'Email',
      subject: 'Asunto',
      message: 'Mensaje',
      submit: 'Enviar',
      success: 'Mensaje enviado. Te respondemos pronto.',
    },
  },
  legal: {
    eyebrow: 'Legal',
    privacyTitle: 'Politica de privacidad',
    privacyDescription: 'Como usamos y protegemos tus datos en FACECARD.',
    cookieTitle: 'Politica de cookies',
    cookieDescription: 'Tipos de cookies y control de consentimiento.',
    cookieSections: [
      {
        title: '1. Cookies esenciales',
        body: 'Garantizan seguridad, sesion y funciones clave de la plataforma.',
      },
      {
        title: '2. Cookies analiticas',
        body: 'Nos ayudan a mejorar rendimiento, contenido y experiencia de navegacion.',
      },
      {
        title: '3. Cookies de marketing',
        body: 'Personalizan mensajes comerciales solo cuando das tu consentimiento.',
      },
      {
        title: '4. Preferencias',
        body: 'Puedes aceptar, rechazar o ajustar cookies opcionales en cualquier momento.',
      },
    ],
    privacySections: [
      {
        title: '1. Responsable',
        body: 'FACECARD gestiona esta plataforma para explorar y reservar talento creativo.',
      },
      {
        title: '2. Datos que usamos',
        body: 'Nombre, email, ciudad, datos de perfil, reservas y metadatos tecnicos.',
      },
      {
        title: '3. Finalidad',
        body: 'Usamos tus datos para acceder, gestionar reservas y mejorar el servicio.',
      },
      {
        title: '4. Conservacion y derechos',
        body: 'Conservamos datos el tiempo necesario. Puedes solicitar acceso, cambio o eliminacion.',
      },
      {
        title: '5. Seguridad',
        body: 'Aplicamos medidas tecnicas y organizativas para proteger tu informacion.',
      },
    ],
  },
  cookies: {
    bannerText:
      'Usamos cookies esenciales para que FACECARD funcione. Puedes aceptar, rechazar o ajustar preferencias.',
    preferences: 'Preferencias',
    reject: 'Rechazar',
    accept: 'Aceptar',
    closeNotice: 'Cerrar aviso de cookies',
    close: 'Cerrar',
    modalTitle: 'Configura cookies',
    essentialTitle: 'Cookies esenciales',
    essentialDescription: 'Necesarias para seguridad, sesion y funciones base.',
    analyticsTitle: 'Cookies analiticas',
    analyticsDescription: 'Nos ayudan a mejorar rendimiento y navegacion.',
    marketingTitle: 'Cookies de marketing',
    marketingDescription: 'Personalizan mensajes comerciales y promocionales.',
    rejectOptional: 'Rechazar opcionales',
    save: 'Guardar preferencias',
  },
  footer: {
    tagline: 'Plataforma premium para reservar talento visual',
    links: {
      contact: 'Contacto',
      privacy: 'Privacidad',
      cookies: 'Cookies',
    },
  },
  notFound: {
    code: '404',
    title: 'Pagina no encontrada',
    description: 'La pagina que buscas no esta disponible.',
    cta: 'Volver al inicio',
  },
}


